# Generated by Django 5.2.11 on 2026-02-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_nom_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abonnement_promo_actif',
            field=models.BooleanField(default=False, help_text='Accès payant à la section Promos'),
        ),
        migrations.AddField(
            model_name='user',
            name='numero_tahiti',
            field=models.CharField(blank=True, default='', help_text='Numéro Tahiti ISPF (obligatoire pour les pros)', max_length=50),
        ),
    ]
