# Generated by Django 5.2.11 on 2026-03-27 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/photos/')),
                ('image_fond', models.ImageField(blank=True, null=True, upload_to='profils/bannieres/')),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('localisation', models.CharField(blank=True, default='', max_length=100)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('site_web', models.URLField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
