# Generated by Django 5.2.11 on 2026-03-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='image_fond_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profil',
            name='photo_profil_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
