# Generated by Django 5.2.11 on 2026-04-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profil_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_imported',
            field=models.BooleanField(db_index=True, default=False, help_text="Compte créé automatiquement depuis l'import petites-annonces.pf"),
        ),
    ]
