# Generated by Django 5.2.11 on 2026-03-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_annonce_boost_duree_boost_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='boost_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='boost_status',
            field=models.CharField(blank=True, choices=[('', 'Sans boost'), ('active', 'Actif'), ('pending', 'En attente'), ('expired', 'Expiré')], default='', max_length=20),
        ),
    ]
