# Generated by Django 5.2.11 on 2026-03-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_merge_electronique_autres_to_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='boost_duree',
            field=models.CharField(blank=True, choices=[('', 'Sans boost'), ('7jours', '7 jours (payant)'), ('1mois', '1 mois (payant)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.CharField(choices=[('vehicules', 'Véhicules'), ('immobilier', 'Immobilier'), ('occasion', 'Occasion'), ('emploi', 'Emploi'), ('services', 'Services')], max_length=50),
        ),
    ]
