# Generated by Django 5.2.11 on 2026-03-21 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_annonce_boost_duree_alter_annonce_categorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='prix_unite',
            field=models.CharField(blank=True, choices=[('', '— Prix fixe'), ('heure', '/ heure'), ('jour', '/ jour'), ('semaine', '/ semaine'), ('mois', '/ mois'), ('unite', '/ unité'), ('negocier', 'À négocier')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='annonce',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AlerteAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('vehicules', 'Véhicules'), ('immobilier', 'Immobilier'), ('occasion', 'Occasion'), ('emploi', 'Emploi'), ('services', 'Services')], max_length=50)),
                ('sous_categorie', models.CharField(blank=True, default='', max_length=50)),
                ('derniere_notification', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte annonce',
                'verbose_name_plural': 'Alertes annonces',
                'unique_together': {('user', 'categorie', 'sous_categorie')},
            },
        ),
    ]
