# Generated by Django 5.2.11 on 2026-03-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_prix_unite_verified_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='clics',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
