# Generated by Django 5.2.11 on 2026-03-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_add_clics_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='type_transaction',
            field=models.CharField(choices=[('non_applicable', 'Non applicable'), ('vente', 'Vente'), ('location', 'Location')], default='non_applicable', max_length=20),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='prix_label',
            field=models.CharField(blank=True, help_text='Ex: 15 000 XPF, Prix sur demande, À débattre', max_length=50),
        ),
    ]
