# Generated by Django 5.2.11 on 2026-03-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_type_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='commune',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='annonce',
            name='precision_lieu',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='annonce',
            name='quartier',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
