# Generated by Django 5.2.11 on 2026-03-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_localisation_commune_quartier'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='derniere_remontee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
