# Generated by Django 5.2.11 on 2026-03-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_derniere_remontee'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='boost_payment_ref',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
