# Generated by Django 5.2.11 on 2026-03-26 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_boost_payment_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerteannonce',
            name='categorie',
            field=models.CharField(choices=[('vehicules', 'Véhicules'), ('immobilier', 'Immobilier'), ('occasion', 'Occasion / Bon Plan'), ('emploi', "Offre et Demande d'emploi"), ('services', 'Service / Prestation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.CharField(choices=[('vehicules', 'Véhicules'), ('immobilier', 'Immobilier'), ('occasion', 'Occasion / Bon Plan'), ('emploi', "Offre et Demande d'emploi"), ('services', 'Service / Prestation')], max_length=50),
        ),
        migrations.CreateModel(
            name='Notation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations_donnees', to=settings.AUTH_USER_MODEL)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations', to='ads.annonce')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notation',
                'verbose_name_plural': 'Notations',
                'ordering': ['-date_creation'],
                'unique_together': {('acheteur', 'vendeur', 'annonce')},
            },
        ),
    ]
