# Generated by Django 5.2.11 on 2026-03-27 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_notation_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notation',
            unique_together={('acheteur', 'vendeur')},
        ),
        migrations.AddField(
            model_name='notation',
            name='avis_ecrit',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.RemoveField(
            model_name='notation',
            name='annonce',
        ),
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enregistrements', to='ads.annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enregistrements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enregistrement',
                'verbose_name_plural': 'Enregistrements',
                'unique_together': {('user', 'annonce')},
            },
        ),
    ]
