# Generated by Django 5.2.11 on 2026-03-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_alter_prix_add_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
