# Generated by Django 5.2.11 on 2026-03-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0021_fix_localisation_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
    ]
