# Generated by Django 5.2.11 on 2026-03-28 22:10

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Annonce = apps.get_model('ads', 'Annonce')
    for annonce in Annonce.objects.all().iterator():
        annonce.slug = f"{slugify(annonce.titre)}-{annonce.pk}"
        annonce.save(update_fields=['slug'])


def reverse_slugs(apps, schema_editor):
    Annonce = apps.get_model('ads', 'Annonce')
    Annonce.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_add_slug_to_annonce'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_slugs),
    ]
