# Generated by Django 5.2.11 on 2026-03-31 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0024_add_photos_thumbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notation',
            name='note',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
