# Generated by Django 5.2.11 on 2026-04-29 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0025_notation_note_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='external_pa_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='annonce',
            name='external_pa_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='annonce',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='imported_seller_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='annonce',
            name='imported_seller_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='annonce',
            name='imported_seller_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='annonce',
            name='is_imported',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['external_pa_id'], name='idx_annonce_pa_id'),
        ),
    ]
