# Generated by Django 5.2.11 on 2026-04-29 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0026_annonce_external_pa_id_annonce_external_pa_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PASyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('success', 'Succès'), ('error', 'Erreur')], default='running', max_length=20)),
                ('nb_created', models.IntegerField(default=0)),
                ('nb_updated', models.IntegerField(default=0)),
                ('nb_archived', models.IntegerField(default=0)),
                ('nb_skipped', models.IntegerField(default=0)),
                ('nb_errors', models.IntegerField(default=0)),
                ('nb_photos', models.IntegerField(default=0)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User qui a lancé manuellement (vide = cron)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync PA',
                'verbose_name_plural': 'Syncs PA',
                'ordering': ['-started_at'],
            },
        ),
    ]
