# Generated by Django 5.2.11 on 2026-04-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0027_pasyncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='fake_saves_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
