# Generated by Django 5.2.11 on 2026-04-10 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('nb_abonnes', models.IntegerField(default=0)),
                ('icone', models.CharField(blank=True, default='💬', max_length=10)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['-nb_abonnes', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nb_vues', models.IntegerField(default=0)),
                ('nb_votes', models.IntegerField(default=0)),
                ('est_epingle', models.BooleanField(default=False)),
                ('est_ferme', models.BooleanField(default=False)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='forum/photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='forum/photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='forum/photos/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_sujets', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to='forum.categorie')),
            ],
            options={
                'verbose_name': 'Sujet',
                'verbose_name_plural': 'Sujets',
                'ordering': ['-est_epingle', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nb_votes', models.IntegerField(default=0)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reponses', to=settings.AUTH_USER_MODEL)),
                ('reponse_parente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_reponses', to='forum.reponse')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='forum.sujet')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'ordering': ['-nb_votes', 'date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AbonnementCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_abonnements', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to='forum.categorie')),
            ],
            options={
                'verbose_name': 'Abonnement catégorie',
                'unique_together': {('utilisateur', 'categorie')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objet', models.CharField(choices=[('sujet', 'Sujet'), ('reponse', 'Réponse')], max_length=10)),
                ('objet_id', models.IntegerField()),
                ('valeur', models.IntegerField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote',
                'unique_together': {('utilisateur', 'type_objet', 'objet_id')},
            },
        ),
    ]
