# Generated by Django 5.2.11 on 2026-04-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='createur',
        ),
        migrations.RemoveField(
            model_name='sujet',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='AbonnementCategorie',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
