# Generated by Django 5.2.11 on 2026-03-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0005_fix_prix_emplacements'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicite',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='pubs/videos/'),
        ),
        migrations.AddField(
            model_name='publicite',
            name='video_url',
            field=models.URLField(blank=True, help_text="URL externe d'une vidéo"),
        ),
    ]
