# Generated by Django 5.2.11 on 2026-03-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0007_publicite_categorie_cat_emplacements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepublicite',
            name='emplacement_souhaite',
            field=models.CharField(choices=[('billboard', 'Billboard plein écran (100 000 XPF/mois)'), ('sidebar_haut', 'Sidebar Droite — Haut (40 000 XPF/mois)'), ('sidebar_milieu', 'Sidebar Droite — Milieu (28 000 XPF/mois)'), ('sidebar_bas', 'Sidebar Droite — Bas (20 000 XPF/mois)'), ('sidebar_gauche', 'Sidebar Gauche (35 000 XPF/mois)'), ('strip_accueil_haut', 'Strip Accueil — Haut (8 000 XPF/mois)'), ('strip_accueil_milieu', 'Strip Accueil — Milieu (8 000 XPF/mois)'), ('strip_accueil_bas', 'Strip Accueil — Bas (8 000 XPF/mois)'), ('strip_immo_haut', 'Strip Immobilier — Haut (12 000 XPF/mois)'), ('strip_immo_milieu', 'Strip Immobilier — Milieu (10 000 XPF/mois)'), ('strip_immo_bas', 'Strip Immobilier — Bas (8 000 XPF/mois)'), ('strip_vehicules_haut', 'Strip Véhicules — Haut (12 000 XPF/mois)'), ('strip_vehicules_milieu', 'Strip Véhicules — Milieu (10 000 XPF/mois)'), ('strip_vehicules_bas', 'Strip Véhicules — Bas (8 000 XPF/mois)'), ('strip_occasion_haut', 'Strip Occasion — Haut (12 000 XPF/mois)'), ('strip_occasion_milieu', 'Strip Occasion — Milieu (10 000 XPF/mois)'), ('strip_occasion_bas', 'Strip Occasion — Bas (8 000 XPF/mois)'), ('strip_emploi_haut', 'Strip Emploi — Haut (12 000 XPF/mois)'), ('strip_emploi_milieu', 'Strip Emploi — Milieu (10 000 XPF/mois)'), ('strip_emploi_bas', 'Strip Emploi — Bas (8 000 XPF/mois)'), ('strip_services_haut', 'Strip Services — Haut (12 000 XPF/mois)'), ('strip_services_milieu', 'Strip Services — Milieu (10 000 XPF/mois)'), ('strip_services_bas', 'Strip Services — Bas (8 000 XPF/mois)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='emplacement',
            field=models.CharField(choices=[('billboard', 'Billboard plein écran (100 000 XPF/mois)'), ('sidebar_haut', 'Sidebar Droite — Haut (40 000 XPF/mois)'), ('sidebar_milieu', 'Sidebar Droite — Milieu (28 000 XPF/mois)'), ('sidebar_bas', 'Sidebar Droite — Bas (20 000 XPF/mois)'), ('sidebar_gauche', 'Sidebar Gauche (35 000 XPF/mois)'), ('strip_accueil_haut', 'Strip Accueil — Haut (8 000 XPF/mois)'), ('strip_accueil_milieu', 'Strip Accueil — Milieu (8 000 XPF/mois)'), ('strip_accueil_bas', 'Strip Accueil — Bas (8 000 XPF/mois)'), ('strip_immo_haut', 'Strip Immobilier — Haut (12 000 XPF/mois)'), ('strip_immo_milieu', 'Strip Immobilier — Milieu (10 000 XPF/mois)'), ('strip_immo_bas', 'Strip Immobilier — Bas (8 000 XPF/mois)'), ('strip_vehicules_haut', 'Strip Véhicules — Haut (12 000 XPF/mois)'), ('strip_vehicules_milieu', 'Strip Véhicules — Milieu (10 000 XPF/mois)'), ('strip_vehicules_bas', 'Strip Véhicules — Bas (8 000 XPF/mois)'), ('strip_occasion_haut', 'Strip Occasion — Haut (12 000 XPF/mois)'), ('strip_occasion_milieu', 'Strip Occasion — Milieu (10 000 XPF/mois)'), ('strip_occasion_bas', 'Strip Occasion — Bas (8 000 XPF/mois)'), ('strip_emploi_haut', 'Strip Emploi — Haut (12 000 XPF/mois)'), ('strip_emploi_milieu', 'Strip Emploi — Milieu (10 000 XPF/mois)'), ('strip_emploi_bas', 'Strip Emploi — Bas (8 000 XPF/mois)'), ('strip_services_haut', 'Strip Services — Haut (12 000 XPF/mois)'), ('strip_services_milieu', 'Strip Services — Milieu (10 000 XPF/mois)'), ('strip_services_bas', 'Strip Services — Bas (8 000 XPF/mois)')], max_length=30),
        ),
    ]
