# Generated by Django 5.2.11 on 2026-03-24 23:45

from django.db import migrations


RENAME_MAP = {
    'haut':       'sidebar_haut',
    'milieu':     'sidebar_milieu',
    'bas':        'sidebar_bas',
    'strip_1':    'strip_accueil_haut',
    'strip_2':    'strip_accueil_milieu',
    'strip_3':    'strip_accueil_bas',
    'cat_haut':   'strip_accueil_haut',   # fallback — will need manual reassignment
    'cat_milieu': 'strip_accueil_milieu',
    'cat_bas':    'strip_accueil_bas',
}

REVERSE_MAP = {v: k for k, v in RENAME_MAP.items()}


def forwards(apps, schema_editor):
    Publicite = apps.get_model('pubs', 'Publicite')
    for old, new in RENAME_MAP.items():
        Publicite.objects.filter(emplacement=old).update(emplacement=new)
    DemandePublicite = apps.get_model('pubs', 'DemandePublicite')
    for old, new in RENAME_MAP.items():
        DemandePublicite.objects.filter(emplacement_souhaite=old).update(emplacement_souhaite=new)


def backwards(apps, schema_editor):
    Publicite = apps.get_model('pubs', 'Publicite')
    for new, old in REVERSE_MAP.items():
        Publicite.objects.filter(emplacement=new).update(emplacement=old)
    DemandePublicite = apps.get_model('pubs', 'DemandePublicite')
    for new, old in REVERSE_MAP.items():
        DemandePublicite.objects.filter(emplacement_souhaite=new).update(emplacement_souhaite=old)


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0008_rename_emplacements'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
