# Generated by Django 5.2.11 on 2026-03-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0009_migrate_emplacement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicite',
            name='categorie',
            field=models.CharField(blank=True, choices=[('vehicules', 'Véhicules'), ('immobilier', 'Immobilier'), ('occasion', 'Occasion / Bon Plan'), ('emploi', "Offre et Demande d'emploi"), ('services', 'Service / Prestation')], default='', help_text='Catégorie ciblée (uniquement pour emplacements cat_*)', max_length=20),
        ),
    ]
